version: "3.8"

services:
  frontend:
    container_name: quiz-web
    build:
      context: ./quiz-web
    ports:
      - "5173:5173"
    volumes:
      - ./quiz-web:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_API_BASE_URL=${API_URL}
      - VITE_FRONT_URL=${CLIENT_URL}
    
  backend:
    container_name: quiz-api
    build:
      context: ./quiz-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CLIENT_URL=${CLIENT_URL}

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quizplatformdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
  node_modules: