version: "3.8"

services:
  web:
    container_name: quiz-web
    build:
      context: ./
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=${API_URL}
      - VITE_FRONT_URL=${CLIENT_URL}
      - VITE_ACCESS_TOKEN_EXPIRATION=${ACCESS_TOKEN_EXPIRATION}