version: '3.8'

services:
  db:
    image: postgres:17
    container_name: local-db
    ports:
      - '5432:5432'
    env_file:
      - .env.development.local
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-net

  api:
    build:
      context: .
      target: development
    container_name: nest-api-dev
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    command: yarn start:dev
    networks:
      - nest-net
    env_file:
      - .env.development.local

volumes:
  pgdata:

networks:
  nest-net:
