export const BASE_QUIZ_SERVICE = Symbol('BASE_QUIZ_SERVICE');
export const QUIZ_SERVICE = Symbol('QUIZ_SERVICE');

export const QUIZ_REPOSITORY = Symbol('QUIZ_REPOSITORY');
export const QUIZ_RESULT_REPOSITORY = Symbol('QUIZ_RESULT_REPOSITORY');
